# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BSPKitExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'BSPKit',   '~> 1.0.1'

  # Pods for BSPKitExample

  target 'BSPKitExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BSPKitExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
